### ISSUE TITLE
Timer resets when moving to another app

### ISSUE THREAD

**Issue by bmbariah** [BCGDV-ASIA/android-widget-ticktock#2]
Is there a way to ensure the timer continues moving even when I'm on another app? and it's in the background?

**Comment by alphamu** [comment]
Keeping animations running in the background is a bad idea. Your best bet is to start the timer in onResume and save it's current state on onPause. If this doesn't help. Let me know what exactly you're trying to do.

**Comment by saadbzu** [comment]
@alphamu I want the same when app close i save the state of timer but how i stat from the same state when user come back? I not see any .getprogress or .setProgress type methods in this lib.
