### ISSUE TITLE
Time not centered!

### ISSUE THREAD

**Issue by GameChangerDF** [BCGDV-ASIA/android-widget-ticktock#4]
How can I fix this problem:

![image](https://cloud.githubusercontent.com/assets/26335897/23815663/c1ad4fd4-05f1-11e7-84a2-ac2bbf352ab2.png)

Thanks! Great work on the widget,

**Comment by alphamu** [comment]
Can you share your code to reproduce the problem? We had singing similar a while back but that issue was fixed. A sample project showing the issue will really help.
