### ISSUE TITLE
Do something once countdown (mCountDown) is over?

### ISSUE THREAD

**Issue by haldertaer** [BCGDV-ASIA/android-widget-ticktock#5]
Hi!

How can I do an action once the countdown (mCountDown) has finished?

Something like this:

mCountDown.OnFinish()
{
      //do something!
}

Thanks.

**Comment by GameChangerDF** [comment]
I'm still looking for a solution...

**Comment by alphamu** [comment]
When the timer finishes, the `getText(int)` method in the `OnTickListener` callback is called with a `0`. You can simply check for this:

       mCountDown.setOnTickListener(new TickTockView.OnTickListener() {
            @Override
            public String getText(long timeRemaining) {
                if (timeRemaining == 0) {
                        // Timer finished, do something.
                }
                int seconds = (int) (timeRemaining / 1000) % 60;
                int minutes = (int) ((timeRemaining / (1000 * 60)) % 60);
                int hours = (int) ((timeRemaining / (1000 * 60 * 60)) % 24);
                int days = (int) (timeRemaining / (1000 * 60 * 60 * 24));
                boolean hasDays = days > 0;
                return String.format("%1$02d%4$s %2$02d%5$s %3$02d%6$s",
                        hasDays ? days : hours,
                        hasDays ? hours : minutes,
                        hasDays ? minutes : seconds,
                        hasDays ? "d" : "h",
                        hasDays ? "h" : "m",
                        hasDays ? "m" : "s");
            }
        });

**Comment by GameChangerDF** [comment]
Thanks a lot!

**Comment by haldertaer** [comment]
Thanks!
