### ISSUE TITLE
How to Write an Action if the countdown time becomes zero??

### ISSUE THREAD

**Issue by hari2babloo** [BCGDV-ASIA/android-widget-ticktock#9]
After the countdown time becomes zero . how to write some action

or how to check if timer becomes zero

**Comment by hari2babloo** [comment]
Text is not coming in the center

**Comment by alphamu** [comment]
You can detect when the clock has hit zero in the update listener.
However, we never planned to support showing some other text in the middle when that happens.
My current suggestion is to put an overlay on top with the text you want.
